- name: Install and configure HAProxy
  hosts: haproxy
  become: yes
  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Copy HAProxy config
      copy:
        src: haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        mode: 0644

    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted
